language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
    - .next
script:
  - yarn test
  - yarn next:build
  - yarn export
deploy:
  provider: surge
  skip_cleanup: true
  domain: new5558.surge.sh
  project: ./next/
  on:
    branch: CICD