language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn gencss
  - yarn next:build
  - yarn export
deploy:
  provider: surge
  skip_cleanup: true
  domain: new5558.surge.sh
  project: ./out/
  on:
    branch: master