language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
    - .next
script:
  # - yarn test
  - yarn next:build
deploy:
  provider: surge
  skip_cleanup: true
  domain: new5558.surge.sh
  project: ./build/
  on:
    branch: master